[phases.setup]
nixPkgs = ["python39", "python39Packages.pip"]

[phases.install]
cmds = [
    "python -m ensurepip --upgrade",
    "python -m pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[start]
cmd = "gunicorn wsgi:app" 